apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsx
  template:
    metadata:
      labels:
        app: devopsx
    spec:
      containers:
      - name: devopsx
        image: devopsx-app:1.2    # <--- NEW TAG
        ports:
        - name: http              # <--- NAMED PORT
          containerPort: 3000
