apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devopsx-servicemonitor
  labels:
    release: monitoring       # MUST match the Helm release name
spec:
  selector:
    matchLabels:
      app: devopsx            # MUST match Service label
  namespaceSelector:
    matchNames:
      - default               # Our app is in 'default' namespace
  endpoints:
    - port: http              # MUST match service port name
      path: /metrics
      interval: 15s
