apiVersion: v1
kind: Service
metadata:
  name: devopsx-service
  labels:
    app: devopsx
spec:
  type: ClusterIP
  selector:
    app: devopsx
  ports:
    - name: http            # <--- NAME MUST MATCH ServiceMonitor
      port: 3000
      targetPort: 3000
